"""Record how a reading's six lines actually arrived.

``/casting/preview`` generates the yarrow and Meihua lines and hands them to
the browser, which posts them back as ``manual_lines``. Coins are tossed in the
browser. Any line can then be hand-edited before submitting. The stored session
said ``method: 五十蓍草法`` in every one of those cases, so a reading opened
later could not be told apart from a hand-entered one.

The preview now signs what it generated. The client echoes the token back, the
server re-derives it, and the session records one of:

``server_cast``
    The lines are exactly what this server generated for that preview.
``client_cast``
    The client says it tossed coins locally; nothing to verify.
``edited``
    A token was supplied but the lines no longer match it.
``manual``
    Hand-entered, or no token supplied.

This is a provenance record, not an access control. A reader may enter whatever
lines they like; the record simply has to say so.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import secrets
from typing import Iterable, Optional, Sequence

#: Set ``ICHING_CASTING_SECRET`` so tokens stay verifiable across workers and
#: restarts. Without it each process signs with its own ephemeral key, so
#: cross-process verification degrades to "unverified" rather than "edited".
_FALLBACK_SECRET = secrets.token_bytes(32)

LINE_SOURCES = ("server_cast", "client_cast", "manual", "edited")


def _secret() -> bytes:
    configured = os.getenv("ICHING_CASTING_SECRET", "")
    return configured.encode("utf-8") if configured else _FALLBACK_SECRET


def _canonical(method_key: str, lines: Iterable[int], timestamp: str) -> bytes:
    joined = ",".join(str(int(value)) for value in lines)
    return f"{method_key}|{joined}|{timestamp}".encode("utf-8")


def sign_cast(method_key: str, lines: Sequence[int], timestamp: str) -> str:
    """Token proving this server produced these lines for this preview."""
    digest = hmac.new(_secret(), _canonical(method_key, lines, timestamp), hashlib.sha256)
    return digest.hexdigest()[:32]


def verify_cast(
    token: Optional[str], method_key: str, lines: Sequence[int], timestamp: str
) -> bool:
    if not token:
        return False
    expected = sign_cast(method_key, lines, timestamp)
    return hmac.compare_digest(token, expected)


def resolve_line_source(
    *,
    method_key: str,
    lines: Sequence[int],
    timestamp: str,
    casting_token: Optional[str],
    declared_source: Optional[str],
) -> str:
    """Classify how these lines arrived, trusting the signature over the claim."""
    if verify_cast(casting_token, method_key, lines, timestamp):
        return "server_cast"
    if casting_token:
        # Signed for a different set of lines: the reader changed them after.
        return "edited"
    if declared_source == "client_cast":
        return "client_cast"
    return "manual"


def describe(line_source: str, locale: str = "zh") -> str:
    labels = {
        "zh": {
            "server_cast": "由服务器按所选起卦法生成，未经改动。",
            "client_cast": "在浏览器本地掷得（三枚铜钱法），服务器未参与生成。",
            "edited": "起卦后手动改过爻值。",
            "manual": "六爻为手动输入。",
        },
        "en": {
            "server_cast": "Generated by the server for the chosen method, unmodified.",
            "client_cast": "Tossed locally in the browser (three-coin method).",
            "edited": "Lines were edited by hand after the cast.",
            "manual": "Lines were entered by hand.",
        },
    }
    table = labels.get("en" if str(locale).startswith("en") else "zh", labels["zh"])
    return table.get(line_source, table["manual"])
