"""Source-backed Zi Ping fact and rule primitives."""

from iching.core.bazi_rules.compiler import (
    COMPILER_VERSION,
    canonical_digest,
    compile_rule_bundle,
    compile_rule_records,
    hydrate_propositions,
    index_hydrated_propositions,
    ingest_rule_definitions,
    load_hydrated_propositions,
)
from iching.core.bazi_rules.adapter import (
    SHADOW_DIFF_REASONS,
    build_source_backed_shadow,
    evaluate_example_attestations,
    fact_graph_matches_pillars,
)
from iching.core.bazi_rules.engine import (
    LIFECYCLE_ENGINE_VERSION,
    LIFECYCLE_STATUSES,
    PatternLifecycleResult,
    evaluate_pattern_lifecycle,
)
from iching.core.bazi_rules.fact_graph import (
    FACT_GRAPH_VERSION,
    build_bazi_fact_envelope,
    build_bazi_fact_envelope_from_graphs,
    build_bazi_fact_graph,
    build_rule_evaluation_context,
)
from iching.core.bazi_rules.predicates import (
    FACT_PATH_REGISTRY,
    OPERATORS,
    PREDICATE_VERSION,
    evaluate_predicate,
    parse_predicate,
)
from iching.core.bazi_rules.primitives import PRIMITIVES_VERSION
from iching.core.bazi_rules.registry import (
    ATTESTATION_BUNDLE_VERSION,
    LIFECYCLE_STAGES,
    REGISTRY_VERSION,
    ExampleAttestation,
    ExampleAttestationBundle,
    RegistryExclusion,
    RegistryRule,
    RegistrySourceProvenance,
    RegistrySourceSegment,
    RegistrySupportLocator,
    RuleRegistry,
    attestation_bundle_from_data,
    compile_research_direct_officer_registry,
    load_packaged_attestation_bundle,
    load_packaged_registry,
    registry_from_data,
    registry_from_records,
)
from iching.core.bazi_rules.schema import (
    ActivationFact,
    BaziFactEnvelope,
    BaziFactGraph,
    CompiledRuleBundle,
    EvaluationResult,
    PredicateNode,
    Proposition,
    RuleDefinition,
    RuleEvaluationContext,
    TruthValue,
)

__all__ = [
    "ActivationFact",
    "ATTESTATION_BUNDLE_VERSION",
    "BaziFactEnvelope",
    "BaziFactGraph",
    "COMPILER_VERSION",
    "CompiledRuleBundle",
    "EvaluationResult",
    "ExampleAttestation",
    "ExampleAttestationBundle",
    "FACT_GRAPH_VERSION",
    "FACT_PATH_REGISTRY",
    "OPERATORS",
    "PREDICATE_VERSION",
    "PRIMITIVES_VERSION",
    "PatternLifecycleResult",
    "PredicateNode",
    "Proposition",
    "RuleDefinition",
    "RuleEvaluationContext",
    "RuleRegistry",
    "RegistryExclusion",
    "RegistryRule",
    "RegistrySourceProvenance",
    "RegistrySourceSegment",
    "RegistrySupportLocator",
    "REGISTRY_VERSION",
    "LIFECYCLE_ENGINE_VERSION",
    "LIFECYCLE_STAGES",
    "LIFECYCLE_STATUSES",
    "SHADOW_DIFF_REASONS",
    "TruthValue",
    "build_bazi_fact_envelope",
    "build_bazi_fact_envelope_from_graphs",
    "build_bazi_fact_graph",
    "build_rule_evaluation_context",
    "build_source_backed_shadow",
    "canonical_digest",
    "compile_rule_bundle",
    "compile_rule_records",
    "compile_research_direct_officer_registry",
    "attestation_bundle_from_data",
    "evaluate_example_attestations",
    "evaluate_pattern_lifecycle",
    "evaluate_predicate",
    "fact_graph_matches_pillars",
    "hydrate_propositions",
    "index_hydrated_propositions",
    "ingest_rule_definitions",
    "load_hydrated_propositions",
    "load_packaged_attestation_bundle",
    "load_packaged_registry",
    "parse_predicate",
    "registry_from_data",
    "registry_from_records",
]
