#!/usr/bin/env python3
"""Generate per-hexagram Chinese copy from the corpus instead of from keywords.

`hexagram-copy.ts` used to build its Chinese gloss by matching a hexagram's
English theme words against ten regexes and filling a template:

    `${short}卦常用于观察${themes}中的局势与变化。`

Nothing in 贲's themes (`form`, `adornment`, `surface`) matched any regex, so
all three collapsed to the 局势 fallback and the page rendered
「贲卦常用于观察局势中的局势与变化。」 — a sentence that says nothing, twice.

Every hexagram already carries its own 大象 and 象曰 in the interpretation
database. This pulls those out so the UI can name what a hexagram is actually
about. Run after `tools/sync_interpretation_db.py`.
"""

from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "data" / "interpretations.db"
LIBRARY_PATH = ROOT / "frontend" / "src" / "lib" / "hexagram-library.ts"
OUTPUT_PATH = ROOT / "frontend" / "src" / "lib" / "hexagram-essence.ts"

# 大象 is a one-line image of the hexagram; 运势 is its situational reading.
IMAGE_RE = re.compile(r"^大象[：:](?P<value>[^\n]+)", re.MULTILINE)
TREND_RE = re.compile(r"^运势[：:](?P<value>[^\n]+)", re.MULTILINE)
XIANG_RE = re.compile(r"^象曰[：:](?P<value>[^\n]+)", re.MULTILINE)
# The 象傳 counsel clause: 君子以… / 先王以… / 后以… / 大人以…
COUNSEL_RE = re.compile(r"(君子以|先王以|后以|大人以|上以)(?P<value>[^\n。；;]+)")


def _library_names() -> dict[str, dict[str, Any]]:
    source = LIBRARY_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        r'\{\s*number:\s*(?P<number>\d+),\s*slug:\s*"(?P<slug>[^"]+)",\s*'
        r'nameZh:\s*"(?P<name_zh>[^"]+)",\s*shortNameZh:\s*"(?P<short>[^"]+)"'
    )
    return {
        m.group("name_zh"): {
            "number": int(m.group("number")),
            "slug": m.group("slug"),
            "short": m.group("short"),
        }
        for m in pattern.finditer(source)
    }


def _clean(value: str | None) -> str:
    if not value:
        return ""
    text = re.sub(r"\s+", "", value).strip()
    text = text.strip("。;；，,")
    return text


def _gua_text() -> dict[str, str]:
    with sqlite3.connect(DB_PATH) as connection:
        rows = connection.execute(
            "SELECT h.name_zh, e.content "
            "FROM interpretation_entry e "
            "JOIN interpretation_slot s ON s.id = e.slot_id "
            "JOIN interpretation_hexagram h ON h.id = s.hexagram_id "
            "JOIN interpretation_source src ON src.id = e.source_id "
            "WHERE s.slot_kind = 'gua' AND src.source_key = 'guaci' "
            "AND e.locale = 'zh-CN' AND e.is_current = 1"
        ).fetchall()
    return {name: content for name, content in rows}


def build() -> list[dict[str, Any]]:
    names = _library_names()
    texts = _gua_text()
    records: list[dict[str, Any]] = []

    for name_zh, meta in names.items():
        content = texts.get(name_zh, "")
        image = _clean(m.group("value") if (m := IMAGE_RE.search(content)) else "")
        trend = _clean(m.group("value") if (m := TREND_RE.search(content)) else "")
        xiang = _clean(m.group("value") if (m := XIANG_RE.search(content)) else "")
        counsel = ""
        if match := COUNSEL_RE.search(xiang or content):
            counsel = _clean(match.group(1) + match.group("value"))

        # 大象 first; otherwise the 象曰 image clause, which every hexagram has.
        if not image and xiang:
            image = _clean(xiang.split("，")[0])

        records.append(
            {
                "number": meta["number"],
                "slug": meta["slug"],
                "nameZh": name_zh,
                "shortNameZh": meta["short"],
                "imageZh": image,
                "counselZh": counsel,
                "trendZh": trend,
            }
        )

    records.sort(key=lambda item: item["number"])
    return records


def main() -> None:
    records = build()
    missing_image = [r["nameZh"] for r in records if not r["imageZh"]]
    missing_counsel = [r["nameZh"] for r in records if not r["counselZh"]]

    lines = [
        "// Generated by tools/build_hexagram_essence.py — do not edit by hand.",
        "//",
        "// Per-hexagram Chinese copy taken from the corpus (大象 / 象曰 / 运势),",
        "// so the UI can say what a hexagram is about instead of filling a",
        "// template from English theme keywords.",
        "",
        "export type HexagramEssence = {",
        "  number: number",
        "  slug: string",
        "  nameZh: string",
        "  shortNameZh: string",
        "  /** 大象: the hexagram's image in one clause. */",
        "  imageZh: string",
        "  /** The 象傳 counsel clause (君子以…). */",
        "  counselZh: string",
        "  /** 运势: how the situation tends to run. */",
        "  trendZh: string",
        "}",
        "",
        "export const HEXAGRAM_ESSENCE: readonly HexagramEssence[] = [",
    ]
    for record in records:
        lines.append("  " + json.dumps(record, ensure_ascii=False) + ",")
    lines.append("]")
    lines.append("")
    lines.append(
        "export const HEXAGRAM_ESSENCE_BY_SLUG: Record<string, HexagramEssence> ="
    )
    lines.append(
        "  Object.fromEntries(HEXAGRAM_ESSENCE.map((item) => [item.slug, item]))"
    )
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)} with {len(records)} hexagrams")
    if missing_image:
        print(f"  no image for: {missing_image}")
    if missing_counsel:
        print(f"  no counsel for: {missing_counsel}")


if __name__ == "__main__":
    main()
