export const HEXAGRAM_LIBRARY = [
  { number: 1, slug: "qian", nameZh: "乾为天", shortNameZh: "乾", titleEn: "The Creative", meaningEn: "strength and creativity", binary: "111111", upper: "Heaven", lower: "Heaven", themes: ["creative power", "initiative", "endurance"] },
  { number: 2, slug: "kun", nameZh: "坤为地", shortNameZh: "坤", titleEn: "The Receptive", meaningEn: "devotion and receptiveness", binary: "000000", upper: "Earth", lower: "Earth", themes: ["receptivity", "support", "field"] },
  { number: 3, slug: "difficulty-at-the-beginning", nameZh: "水雷屯", shortNameZh: "屯", titleEn: "Difficulty at the Beginning", meaningEn: "hardship and perseverance", binary: "100010", upper: "Water", lower: "Thunder", themes: ["beginning", "confusion", "first commitment"] },
  { number: 4, slug: "youthful-folly", nameZh: "山水蒙", shortNameZh: "蒙", titleEn: "Youthful Folly", meaningEn: "inexperience and learning", binary: "010001", upper: "Mountain", lower: "Water", themes: ["learning", "instruction", "limits"] },
  { number: 5, slug: "waiting", nameZh: "水天需", shortNameZh: "需", titleEn: "Waiting", meaningEn: "patience and preparedness", binary: "111010", upper: "Water", lower: "Heaven", themes: ["timing", "patience", "resources"] },
  { number: 6, slug: "conflict", nameZh: "天水讼", shortNameZh: "讼", titleEn: "Conflict", meaningEn: "disagreement and caution", binary: "010111", upper: "Heaven", lower: "Water", themes: ["dispute", "restraint", "process"] },
  { number: 7, slug: "the-army", nameZh: "地水师", shortNameZh: "师", titleEn: "The Army", meaningEn: "leadership and organization", binary: "010000", upper: "Earth", lower: "Water", themes: ["discipline", "organization", "command"] },
  { number: 8, slug: "holding-together", nameZh: "水地比", shortNameZh: "比", titleEn: "Holding Together", meaningEn: "unity and shared goals", binary: "000010", upper: "Water", lower: "Earth", themes: ["alliance", "belonging", "selection"] },
  { number: 9, slug: "small-taming", nameZh: "风天小畜", shortNameZh: "小畜", titleEn: "Small Taming", meaningEn: "small challenges to be overcome", binary: "111011", upper: "Wind", lower: "Heaven", themes: ["restraint", "accumulation", "small force"] },
  { number: 10, slug: "treading", nameZh: "天泽履", shortNameZh: "履", titleEn: "Treading", meaningEn: "prudence and caution", binary: "110111", upper: "Heaven", lower: "Lake", themes: ["conduct", "risk", "protocol"] },
  { number: 11, slug: "peace", nameZh: "地天泰", shortNameZh: "泰", titleEn: "Peace", meaningEn: "harmony and balance", binary: "111000", upper: "Earth", lower: "Heaven", themes: ["flow", "exchange", "prosperity"] },
  { number: 12, slug: "standstill", nameZh: "天地否", shortNameZh: "否", titleEn: "Standstill", meaningEn: "stagnation and waiting", binary: "000111", upper: "Heaven", lower: "Earth", themes: ["blockage", "separation", "withholding"] },
  { number: 13, slug: "fellowship", nameZh: "天火同人", shortNameZh: "同人", titleEn: "Fellowship with Men", meaningEn: "teamwork and collaboration", binary: "101111", upper: "Heaven", lower: "Fire", themes: ["fellowship", "public cause", "alignment"] },
  { number: 14, slug: "great-possession", nameZh: "火天大有", shortNameZh: "大有", titleEn: "Great Possession", meaningEn: "wealth and abundance", binary: "111101", upper: "Fire", lower: "Heaven", themes: ["abundance", "responsibility", "visibility"] },
  { number: 15, slug: "modesty", nameZh: "地山谦", shortNameZh: "谦", titleEn: "Modesty", meaningEn: "humility and groundedness", binary: "001000", upper: "Earth", lower: "Mountain", themes: ["modesty", "calibration", "measure"] },
  { number: 16, slug: "enthusiasm", nameZh: "雷地豫", shortNameZh: "豫", titleEn: "Enthusiasm", meaningEn: "vitality and optimism", binary: "000100", upper: "Thunder", lower: "Earth", themes: ["mobilization", "readiness", "inspiration"] },
  { number: 17, slug: "following", nameZh: "泽雷随", shortNameZh: "随", titleEn: "Following", meaningEn: "adherence and guidance", binary: "100110", upper: "Lake", lower: "Thunder", themes: ["following", "response", "adaptation"] },
  { number: 18, slug: "work-on-what-has-been-spoiled", nameZh: "山风蛊", shortNameZh: "蛊", titleEn: "Work on What Has Been Spoiled", meaningEn: "improvement and renewal", binary: "011001", upper: "Mountain", lower: "Wind", themes: ["repair", "decay", "ancestral pattern"] },
  { number: 19, slug: "approach", nameZh: "地泽临", shortNameZh: "临", titleEn: "Approach", meaningEn: "progress and new beginnings", binary: "110000", upper: "Earth", lower: "Lake", themes: ["approach", "oversight", "arrival"] },
  { number: 20, slug: "contemplation", nameZh: "风地观", shortNameZh: "观", titleEn: "Contemplation", meaningEn: "observation and introspection", binary: "000011", upper: "Wind", lower: "Earth", themes: ["observation", "example", "ritual view"] },
  { number: 21, slug: "biting-through", nameZh: "火雷噬嗑", shortNameZh: "噬嗑", titleEn: "Biting Through", meaningEn: "action and resolution", binary: "100101", upper: "Fire", lower: "Thunder", themes: ["enforcement", "clarity", "obstruction"] },
  { number: 22, slug: "grace", nameZh: "山火贲", shortNameZh: "贲", titleEn: "Grace", meaningEn: "beauty and form", binary: "101001", upper: "Mountain", lower: "Fire", themes: ["form", "adornment", "surface"] },
  { number: 23, slug: "splitting-apart", nameZh: "山地剥", shortNameZh: "剥", titleEn: "Splitting Apart", meaningEn: "separation and release", binary: "000001", upper: "Mountain", lower: "Earth", themes: ["stripping", "decline", "erosion"] },
  { number: 24, slug: "return", nameZh: "地雷复", shortNameZh: "复", titleEn: "Return", meaningEn: "renewal and returning to the source", binary: "100000", upper: "Earth", lower: "Thunder", themes: ["return", "renewal", "cycle"] },
  { number: 25, slug: "innocence", nameZh: "天雷无妄", shortNameZh: "无妄", titleEn: "Innocence", meaningEn: "simplicity and purity", binary: "100111", upper: "Heaven", lower: "Thunder", themes: ["naturalness", "unexpected", "truth"] },
  { number: 26, slug: "great-taming", nameZh: "山天大畜", shortNameZh: "大畜", titleEn: "The Taming Power of the Great", meaningEn: "control and restraint", binary: "111001", upper: "Mountain", lower: "Heaven", themes: ["stored power", "training", "restraint"] },
  { number: 27, slug: "nourishment", nameZh: "山雷颐", shortNameZh: "颐", titleEn: "The Corners of the Mouth", meaningEn: "nourishment and health", binary: "100001", upper: "Mountain", lower: "Thunder", themes: ["nourishment", "speech", "feeding"] },
  { number: 28, slug: "great-preponderance", nameZh: "泽风大过", shortNameZh: "大过", titleEn: "Preponderance of the Great", meaningEn: "excess and responsibility", binary: "011110", upper: "Lake", lower: "Wind", themes: ["overload", "weight", "extraordinary action"] },
  { number: 29, slug: "the-abysmal", nameZh: "坎为水", shortNameZh: "坎", titleEn: "The Abysmal", meaningEn: "danger and unpredictability", binary: "010010", upper: "Water", lower: "Water", themes: ["danger", "depth", "repetition"] },
  { number: 30, slug: "the-clinging", nameZh: "离为火", shortNameZh: "离", titleEn: "The Clinging", meaningEn: "clarity and illumination", binary: "101101", upper: "Fire", lower: "Fire", themes: ["clarity", "attachment", "brightness"] },
  { number: 31, slug: "influence", nameZh: "泽山咸", shortNameZh: "咸", titleEn: "Influence", meaningEn: "attraction and impact", binary: "001110", upper: "Lake", lower: "Mountain", themes: ["influence", "attraction", "response"] },
  { number: 32, slug: "duration", nameZh: "雷风恒", shortNameZh: "恒", titleEn: "Duration", meaningEn: "stability and persistence", binary: "011100", upper: "Thunder", lower: "Wind", themes: ["duration", "constancy", "vow"] },
  { number: 33, slug: "retreat", nameZh: "天山遁", shortNameZh: "遁", titleEn: "Retreat", meaningEn: "strategic withdrawal", binary: "001111", upper: "Heaven", lower: "Mountain", themes: ["retreat", "distance", "preservation"] },
  { number: 34, slug: "great-power", nameZh: "雷天大壮", shortNameZh: "大壮", titleEn: "Great Power", meaningEn: "strength and assertiveness", binary: "111100", upper: "Thunder", lower: "Heaven", themes: ["power", "restraint", "strength"] },
  { number: 35, slug: "progress", nameZh: "火地晋", shortNameZh: "晋", titleEn: "Progress", meaningEn: "movement and development", binary: "000101", upper: "Fire", lower: "Earth", themes: ["progress", "recognition", "advance"] },
  { number: 36, slug: "darkening-of-the-light", nameZh: "地火明夷", shortNameZh: "明夷", titleEn: "Darkening of the Light", meaningEn: "caution and temporary restraint", binary: "101000", upper: "Earth", lower: "Fire", themes: ["concealment", "injury", "hidden light"] },
  { number: 37, slug: "the-family", nameZh: "风火家人", shortNameZh: "家人", titleEn: "The Family", meaningEn: "kinship and loyalty", binary: "101011", upper: "Wind", lower: "Fire", themes: ["household", "roles", "inner order"] },
  { number: 38, slug: "opposition", nameZh: "火泽睽", shortNameZh: "睽", titleEn: "Opposition", meaningEn: "conflict and contrast", binary: "110101", upper: "Fire", lower: "Lake", themes: ["opposition", "difference", "small accord"] },
  { number: 39, slug: "obstruction", nameZh: "水山蹇", shortNameZh: "蹇", titleEn: "Obstruction", meaningEn: "blockage and barriers", binary: "001010", upper: "Water", lower: "Mountain", themes: ["obstruction", "difficulty", "detour"] },
  { number: 40, slug: "deliverance", nameZh: "雷水解", shortNameZh: "解", titleEn: "Deliverance", meaningEn: "freedom and release", binary: "010100", upper: "Thunder", lower: "Water", themes: ["release", "solution", "untying"] },
  { number: 41, slug: "decrease", nameZh: "山泽损", shortNameZh: "损", titleEn: "Decrease", meaningEn: "loss and humility", binary: "110001", upper: "Mountain", lower: "Lake", themes: ["decrease", "offering", "simplification"] },
  { number: 42, slug: "increase", nameZh: "风雷益", shortNameZh: "益", titleEn: "Increase", meaningEn: "growth and prosperity", binary: "100011", upper: "Wind", lower: "Thunder", themes: ["increase", "benefit", "movement"] },
  { number: 43, slug: "breakthrough", nameZh: "泽天夬", shortNameZh: "夬", titleEn: "Breakthrough", meaningEn: "achievement and success", binary: "111110", upper: "Lake", lower: "Heaven", themes: ["decision", "declaration", "breakthrough"] },
  { number: 44, slug: "coming-to-meet", nameZh: "天风姤", shortNameZh: "姤", titleEn: "Coming to Meet", meaningEn: "interaction and opportunity", binary: "011111", upper: "Heaven", lower: "Wind", themes: ["encounter", "temptation", "arrival"] },
  { number: 45, slug: "gathering-together", nameZh: "泽地萃", shortNameZh: "萃", titleEn: "Gathering Together", meaningEn: "unity and convergence", binary: "000110", upper: "Lake", lower: "Earth", themes: ["gathering", "assembly", "offering"] },
  { number: 46, slug: "pushing-upward", nameZh: "地风升", shortNameZh: "升", titleEn: "Pushing Upward", meaningEn: "progress and aspiration", binary: "011000", upper: "Earth", lower: "Wind", themes: ["ascent", "growth", "patient rise"] },
  { number: 47, slug: "oppression", nameZh: "泽水困", shortNameZh: "困", titleEn: "Oppression", meaningEn: "hardship and exhaustion", binary: "010110", upper: "Lake", lower: "Water", themes: ["constraint", "exhaustion", "inner truth"] },
  { number: 48, slug: "the-well", nameZh: "水风井", shortNameZh: "井", titleEn: "The Well", meaningEn: "resources and nourishment", binary: "011010", upper: "Water", lower: "Wind", themes: ["source", "resource", "maintenance"] },
  { number: 49, slug: "revolution", nameZh: "泽火革", shortNameZh: "革", titleEn: "Revolution", meaningEn: "transformation and change", binary: "101110", upper: "Lake", lower: "Fire", themes: ["change", "mandate", "renewal"] },
  { number: 50, slug: "the-cauldron", nameZh: "火风鼎", shortNameZh: "鼎", titleEn: "The Cauldron", meaningEn: "nourishment and culture", binary: "011101", upper: "Fire", lower: "Wind", themes: ["vessel", "culture", "transformation"] },
  { number: 51, slug: "the-arousing", nameZh: "震为雷", shortNameZh: "震", titleEn: "The Arousing", meaningEn: "shock and movement", binary: "100100", upper: "Thunder", lower: "Thunder", themes: ["shock", "awakening", "movement"] },
  { number: 52, slug: "keeping-still", nameZh: "艮为山", shortNameZh: "艮", titleEn: "Keeping Still", meaningEn: "tranquility and meditation", binary: "001001", upper: "Mountain", lower: "Mountain", themes: ["stillness", "boundary", "rest"] },
  { number: 53, slug: "development", nameZh: "风山渐", shortNameZh: "渐", titleEn: "Development", meaningEn: "gradual progress", binary: "001011", upper: "Wind", lower: "Mountain", themes: ["gradualness", "marriage", "sequence"] },
  { number: 54, slug: "the-marrying-maiden", nameZh: "雷泽归妹", shortNameZh: "归妹", titleEn: "The Marrying Maiden", meaningEn: "relationships and adaptation", binary: "110100", upper: "Thunder", lower: "Lake", themes: ["secondary role", "relationship", "improper timing"] },
  { number: 55, slug: "abundance", nameZh: "雷火丰", shortNameZh: "丰", titleEn: "Abundance", meaningEn: "wealth and prosperity", binary: "101100", upper: "Thunder", lower: "Fire", themes: ["abundance", "fullness", "eclipse"] },
  { number: 56, slug: "the-wanderer", nameZh: "火山旅", shortNameZh: "旅", titleEn: "The Wanderer", meaningEn: "journeys and exploration", binary: "001101", upper: "Fire", lower: "Mountain", themes: ["travel", "temporary place", "care"] },
  { number: 57, slug: "the-gentle", nameZh: "巽为风", shortNameZh: "巽", titleEn: "The Gentle", meaningEn: "influence and flexibility", binary: "011011", upper: "Wind", lower: "Wind", themes: ["penetration", "gentleness", "influence"] },
  { number: 58, slug: "the-joyous", nameZh: "兑为泽", shortNameZh: "兑", titleEn: "The Joyous", meaningEn: "pleasure and satisfaction", binary: "110110", upper: "Lake", lower: "Lake", themes: ["joy", "speech", "exchange"] },
  { number: 59, slug: "dispersion", nameZh: "风水涣", shortNameZh: "涣", titleEn: "Dispersion", meaningEn: "scattering and renewal", binary: "010011", upper: "Wind", lower: "Water", themes: ["dispersion", "release", "reunion"] },
  { number: 60, slug: "limitation", nameZh: "水泽节", shortNameZh: "节", titleEn: "Limitation", meaningEn: "restraint and order", binary: "110010", upper: "Water", lower: "Lake", themes: ["measure", "limit", "discipline"] },
  { number: 61, slug: "inner-truth", nameZh: "风泽中孚", shortNameZh: "中孚", titleEn: "Inner Truth", meaningEn: "sincerity and communication", binary: "110011", upper: "Wind", lower: "Lake", themes: ["trust", "inner truth", "communication"] },
  { number: 62, slug: "small-exceeding", nameZh: "雷山小过", shortNameZh: "小过", titleEn: "Small Exceeding", meaningEn: "minor excesses and adjustments", binary: "001100", upper: "Thunder", lower: "Mountain", themes: ["small excess", "care", "low flight"] },
  { number: 63, slug: "after-completion", nameZh: "水火既济", shortNameZh: "既济", titleEn: "After Completion", meaningEn: "the successful conclusion", binary: "101010", upper: "Water", lower: "Fire", themes: ["completion", "maintenance", "fragility"] },
  { number: 64, slug: "before-completion", nameZh: "火水未济", shortNameZh: "未济", titleEn: "Before Completion", meaningEn: "preparation and anticipation", binary: "010101", upper: "Fire", lower: "Water", themes: ["unfinished", "threshold", "careful crossing"] },
] as const

export const HEXAGRAM_PINYIN_BY_SLUG: Record<(typeof HEXAGRAM_LIBRARY)[number]["slug"], string> = {
  qian: "Qián",
  kun: "Kūn",
  "difficulty-at-the-beginning": "Zhūn",
  "youthful-folly": "Méng",
  waiting: "Xū",
  conflict: "Sòng",
  "the-army": "Shī",
  "holding-together": "Bǐ",
  "small-taming": "Xiǎo Chù",
  treading: "Lǚ",
  peace: "Tài",
  standstill: "Pǐ",
  fellowship: "Tóng Rén",
  "great-possession": "Dà Yǒu",
  modesty: "Qiān",
  enthusiasm: "Yù",
  following: "Suí",
  "work-on-what-has-been-spoiled": "Gǔ",
  approach: "Lín",
  contemplation: "Guān",
  "biting-through": "Shì Kè",
  grace: "Bì",
  "splitting-apart": "Bō",
  return: "Fù",
  innocence: "Wú Wàng",
  "great-taming": "Dà Chù",
  nourishment: "Yí",
  "great-preponderance": "Dà Guò",
  "the-abysmal": "Kǎn",
  "the-clinging": "Lí",
  influence: "Xián",
  duration: "Héng",
  retreat: "Dùn",
  "great-power": "Dà Zhuàng",
  progress: "Jìn",
  "darkening-of-the-light": "Míng Yí",
  "the-family": "Jiā Rén",
  opposition: "Kuí",
  obstruction: "Jiǎn",
  deliverance: "Xiè",
  decrease: "Sǔn",
  increase: "Yì",
  breakthrough: "Guài",
  "coming-to-meet": "Gòu",
  "gathering-together": "Cuì",
  "pushing-upward": "Shēng",
  oppression: "Kùn",
  "the-well": "Jǐng",
  revolution: "Gé",
  "the-cauldron": "Dǐng",
  "the-arousing": "Zhèn",
  "keeping-still": "Gèn",
  development: "Jiàn",
  "the-marrying-maiden": "Guī Mèi",
  abundance: "Fēng",
  "the-wanderer": "Lǚ",
  "the-gentle": "Xùn",
  "the-joyous": "Duì",
  dispersion: "Huàn",
  limitation: "Jié",
  "inner-truth": "Zhōng Fú",
  "small-exceeding": "Xiǎo Guò",
  "after-completion": "Jì Jì",
  "before-completion": "Wèi Jì",
}

export type HexagramLibraryEntry = (typeof HEXAGRAM_LIBRARY)[number]

export function getHexagramBySlug(slug: string) {
  return HEXAGRAM_LIBRARY.find((entry) => entry.slug === slug)
}

export function getHexagramPinyin(slug: HexagramLibraryEntry["slug"] | string) {
  return HEXAGRAM_PINYIN_BY_SLUG[slug as HexagramLibraryEntry["slug"]] ?? ""
}

export function hexagramLines(binary: string) {
  return binary.split("").reverse() as Array<"0" | "1">
}
