// Generated by tools/build_hexagram_essence.py — do not edit by hand.
//
// Per-hexagram Chinese copy taken from the corpus (大象 / 象曰 / 运势),
// so the UI can say what a hexagram is about instead of filling a
// template from English theme keywords.

export type HexagramEssence = {
  number: number
  slug: string
  nameZh: string
  shortNameZh: string
  /** 大象: the hexagram's image in one clause. */
  imageZh: string
  /** The 象傳 counsel clause (君子以…). */
  counselZh: string
  /** 运势: how the situation tends to run. */
  trendZh: string
}

export const HEXAGRAM_ESSENCE: readonly HexagramEssence[] = [
  {"number": 1, "slug": "qian", "nameZh": "乾为天", "shortNameZh": "乾", "imageZh": "天行刚健，自强不息", "counselZh": "君子以自强不息", "trendZh": "飞龙在天，名利双收之象，宜把握机会，争取成果"},
  {"number": 2, "slug": "kun", "nameZh": "坤为地", "shortNameZh": "坤", "imageZh": "大地承载万物，以德服众，仁者无敌", "counselZh": "君子以厚德载物", "trendZh": "诸事不宜急进，以静制动为宜"},
  {"number": 3, "slug": "difficulty-at-the-beginning", "nameZh": "水雷屯", "shortNameZh": "屯", "imageZh": "屯者难也，万事欲进而不得进", "counselZh": "君子以经纶", "trendZh": "身处困境，步步为营，有初难后解之意"},
  {"number": 4, "slug": "youthful-folly", "nameZh": "山水蒙", "shortNameZh": "蒙", "imageZh": "蒙者，昏而无所见也，故宜「启蒙」", "counselZh": "君子以果行育德", "trendZh": "初时迷惑不知方向，须忍耐待机而动，凡事多听取别人意见，则运可通"},
  {"number": 5, "slug": "waiting", "nameZh": "水天需", "shortNameZh": "需", "imageZh": "云登天上而未雨，不能急进，等待时机之象", "counselZh": "君子以饮食宴乐", "trendZh": "智者必须待时而行，急进反见凶险"},
  {"number": 6, "slug": "conflict", "nameZh": "天水讼", "shortNameZh": "讼", "imageZh": "乾天升于上，坎水降于下，相背而行而起讼", "counselZh": "君子以做事谋始", "trendZh": "事与愿违，凡事不顺，小人加害，宜防陷阱"},
  {"number": 7, "slug": "the-army", "nameZh": "地水师", "shortNameZh": "师", "imageZh": "养兵聚众，出师攻伐之象，彼此有伤，难得安宁", "counselZh": "君子以容民畜众", "trendZh": "困难重重，凡事以正规行事，忌独断独行、投机取巧，提防潜在敌人"},
  {"number": 8, "slug": "holding-together", "nameZh": "水地比", "shortNameZh": "比", "imageZh": "一阳统五阴，比邻相亲相辅，和乐之象", "counselZh": "先王以建万国，亲诸侯", "trendZh": "平顺，可得贵人提拔，凡事宜速战速决，不可过份迟疑"},
  {"number": 9, "slug": "small-taming", "nameZh": "风天小畜", "shortNameZh": "小畜", "imageZh": "蓄养之量有限，力不从心，故宜忍耐蓄养实力，静待时机", "counselZh": "君子以懿文德", "trendZh": "运势反覆，有口舌之争，但难于短期内解决，须忍耐，静待时机"},
  {"number": 10, "slug": "treading", "nameZh": "天泽履", "shortNameZh": "履", "imageZh": "柔弱遇刚强，欲行却难行之象，难且危也", "counselZh": "君子以辨上下，定民志", "trendZh": "先劳而后逸，始惊而后安，百事不宜急进，须以和待人，有惊无险"},
  {"number": 11, "slug": "peace", "nameZh": "地天泰", "shortNameZh": "泰", "imageZh": "天地交泰，上下相通，阴阳和畅，万物通达", "counselZh": "后以财成天地之道，辅相天地之宜，以左右民", "trendZh": "处境顺畅，宜把握可通之时推进正事；泰极而否，盛时更须守正防满"},
  {"number": 12, "slug": "standstill", "nameZh": "天地否", "shortNameZh": "否", "imageZh": "天气上升，地气下降，天地之气不交，主闭塞不通", "counselZh": "君子以俭德辟难，不可荣以禄", "trendZh": "上下不和，百事不通，凡事宜忍，须知否极泰来"},
  {"number": 13, "slug": "fellowship", "nameZh": "天火同人", "shortNameZh": "同人", "imageZh": "二人同心，其利断金，君子正心诚意，与人和同之象", "counselZh": "君子以类族辨物", "trendZh": "如意吉祥，与人共事，上下皆和，又得长辈提拔"},
  {"number": 14, "slug": "great-possession", "nameZh": "火天大有", "shortNameZh": "大有", "imageZh": "太阳在天，遍照大地万物，但五阳争一阴，须知有盈即缺", "counselZh": "君子以遏恶扬善，顺天休命", "trendZh": "得时得运，昌荣大吉，但防物极必反，盛极而衰"},
  {"number": 15, "slug": "modesty", "nameZh": "地山谦", "shortNameZh": "谦", "imageZh": "山应在地面上，而今在地下，代表谦逊之德", "counselZh": "君子以裒多益寡，称物平施", "trendZh": "吉利平安，前途无限，但必须去除骄横之气"},
  {"number": 16, "slug": "enthusiasm", "nameZh": "雷地豫", "shortNameZh": "豫", "imageZh": "雷出于地上，阳气奋发，万物欣欣向荣", "counselZh": "先王以作乐崇德，殷荐之上帝，以配祖考", "trendZh": "如意安泰，可得长辈扶助，但须防色难，凡事应有备而战"},
  {"number": 17, "slug": "following", "nameZh": "泽雷随", "shortNameZh": "随", "imageZh": "震木在兑泽之下，木必随水漂荡，随者，顺也", "counselZh": "君子以向晦入宴息", "trendZh": "有去旧迎新之吉象，宜与人合作，可获厚利，忌三心两意，或独断独行"},
  {"number": 18, "slug": "work-on-what-has-been-spoiled", "nameZh": "山风蛊", "shortNameZh": "蛊", "imageZh": "风入山下，闭而不出，即物腐生虫，意气不通，因循败事", "counselZh": "君子以振民育德", "trendZh": "诸事不如意，艰难迷惑，宜大胆革新，否则引来内忧外患"},
  {"number": 19, "slug": "approach", "nameZh": "地泽临", "shortNameZh": "临", "imageZh": "池泽之水灌溉地面万物，相辅相成，生生不息", "counselZh": "君子以教思无穷，客保民无疆", "trendZh": "诸事亨通，上下和合，前途有望，但不宜过于急进"},
  {"number": 20, "slug": "contemplation", "nameZh": "风地观", "shortNameZh": "观", "imageZh": "风运行于坤地之上，喻有周游观览之意。阴长阳消，正道衰微，万物难行", "counselZh": "先王以省方，观民设教", "trendZh": "处身于变化之中，宜多观察入微，心身苦恼，并防外来诱惑"},
  {"number": 21, "slug": "biting-through", "nameZh": "火雷噬嗑", "shortNameZh": "噬嗑", "imageZh": "上唇与下唇间有物，必须咬断，方能合拢，乃诸事被阻，务必去除，方可成功", "counselZh": "先王以明罚敕法", "trendZh": "诸事阻隔，纷争难免，宜守常规，不为利诱，问题可解决"},
  {"number": 22, "slug": "grace", "nameZh": "山火贲", "shortNameZh": "贲", "imageZh": "日落西山，照耀通明，华美灿烂，同时喻光明力量渐消，阴暗的力量扩大", "counselZh": "君子以明庶政，无敢折狱", "trendZh": "表面风光，内里空虚，必须充实自己，凡事宜踏实、按部就班"},
  {"number": 23, "slug": "splitting-apart", "nameZh": "山地剥", "shortNameZh": "剥", "imageZh": "山附于地喻山石崩而落于地面上，五阴迫一阳，正义被损", "counselZh": "上以厚下，安宅", "trendZh": "恶运缠身，宜重新部署，不宜自作聪明，防被女子及小人连累"},
  {"number": 24, "slug": "return", "nameZh": "地雷复", "shortNameZh": "复", "imageZh": "雷在地中振发，喻春回大地，一元始，万象更生", "counselZh": "先王以至日闭关，商旅不行，后不省方", "trendZh": "开运亨通之象，万事不宜急进，按部就班可成"},
  {"number": 25, "slug": "innocence", "nameZh": "天雷无妄", "shortNameZh": "无妄", "imageZh": "雷动于天，阳气舒发，为真实无虚妄之意", "counselZh": "先王以茂对时，育万物", "trendZh": "凡事宜守正，若行为不检者，必招灾祸"},
  {"number": 26, "slug": "great-taming", "nameZh": "山天大畜", "shortNameZh": "大畜", "imageZh": "天之大而在山之中，以小阻大，以阴畜阳，为止为养", "counselZh": "君子以多识前言往行，以畜其德", "trendZh": "处事不可好高骛远，宜脚踏实地，可成大业，忌目空一切"},
  {"number": 27, "slug": "nourishment", "nameZh": "山雷颐", "shortNameZh": "颐", "imageZh": "形如口腔之象，取其饮食之道，须慎言，注重日常生活", "counselZh": "君子以慎言语，节饮食", "trendZh": "处事欠缺周详考虑，不宜心怀阴谋，要守正道而善方吉"},
  {"number": 28, "slug": "great-preponderance", "nameZh": "泽风大过", "shortNameZh": "大过", "imageZh": "中间四阳爻，为结实之梁，但初末为阴爻，力弱不支，则势将摧折", "counselZh": "君子以独立不惧，遁世无闷", "trendZh": "有力不从心，负担过重之象，多烦恼，防官非及水险"},
  {"number": 29, "slug": "the-abysmal", "nameZh": "坎为水", "shortNameZh": "坎", "imageZh": "两水重叠，坎水为险，进固险，退亦险，进退两难", "counselZh": "君子以常德行，习教事", "trendZh": "危机重重，宜沉著应付，保持心境开朗，凡事莫与人争"},
  {"number": 30, "slug": "the-clinging", "nameZh": "离为火", "shortNameZh": "离", "imageZh": "两离火相重，上下通明之象，火有气，但无形，主不实不定之意", "counselZh": "大人以继明照四方", "trendZh": "外观极盛，烈日当空之象，凡事不宜急进及意气用事"},
  {"number": 31, "slug": "influence", "nameZh": "泽山咸", "shortNameZh": "咸", "imageZh": "少男在少女之下，彼此感应，象征新婚，两性交感", "counselZh": "君子以虚受人", "trendZh": "如意吉祥，但勿为不正当感情而意乱情迷"},
  {"number": 32, "slug": "duration", "nameZh": "雷风恒", "shortNameZh": "恒", "imageZh": "震者为动，宜向外发展，巽为入，为内向，一内一外，各居本位，故能永恒不变，喻夫妇之道", "counselZh": "君子以立不易方", "trendZh": "万事亨通，能恒久努力，安守本份则吉，妄动则招灾"},
  {"number": 33, "slug": "retreat", "nameZh": "天山遁", "shortNameZh": "遁", "imageZh": "山在天之下，阴渐长，而阳渐消，宜退避三舍", "counselZh": "君子以远小人，不恶而严", "trendZh": "小人道长，君子道消，凡事宜退不宜进，穷则独善其身，修身养性"},
  {"number": 34, "slug": "great-power", "nameZh": "雷天大壮", "shortNameZh": "大壮", "imageZh": "雷声响亮，光明天际，为正大光明之象，又为强烈地动之象，为六冲卦之一", "counselZh": "君子以非礼弗履", "trendZh": "运势虽强，但已届极盛之时，宜心平气和，否则反招失败，须知物极必反"},
  {"number": 35, "slug": "progress", "nameZh": "火地晋", "shortNameZh": "晋", "imageZh": "日出地面，普照大地，有光明上进之象", "counselZh": "君子以自昭明德", "trendZh": "事业、名望、财运皆吉，所谓有加官晋爵之兆"},
  {"number": 36, "slug": "darkening-of-the-light", "nameZh": "地火明夷", "shortNameZh": "明夷", "imageZh": "太阳掩没在坤地之下，大地黑暗，有失明之象", "counselZh": "君子以莅众，用晦而明", "trendZh": "百事阻滞，小人加害，遇事多迷惑，宜守，静待时机而动"},
  {"number": 37, "slug": "the-family", "nameZh": "风火家人", "shortNameZh": "家人", "imageZh": "风吹火之象，助火之威，喻家人同心协力，发展事业", "counselZh": "君子以言有物，而行有恒", "trendZh": "平安大吉，与人合作则易成，更有喜庆之象，如添丁婚嫁等"},
  {"number": 38, "slug": "opposition", "nameZh": "火泽睽", "shortNameZh": "睽", "imageZh": "离火向上，兑泽则向下，一上一下，两相乖违，又二女同居，不得正之象", "counselZh": "君子以同而异", "trendZh": "气运欠佳，诸事难成，有水火不容之象，宜处变不惊"},
  {"number": 39, "slug": "obstruction", "nameZh": "水山蹇", "shortNameZh": "蹇", "imageZh": "前路险陷，后有高山，进退维谷，如跛者举步为艰", "counselZh": "君子以反身修德", "trendZh": "多灾多难，进退两难，此时宜守正道，不可轻举妄动，动反招祸"},
  {"number": 40, "slug": "deliverance", "nameZh": "雷水解", "shortNameZh": "解", "imageZh": "春雷大作，大地解冻，喻冬去春来生机再现", "counselZh": "君子以赦过宥罪", "trendZh": "宜把握良机，快速处理身边困境，更宜出外求谋，因贵人在远方，以西南为吉方"},
  {"number": 41, "slug": "decrease", "nameZh": "山泽损", "shortNameZh": "损", "imageZh": "山高水深，各得其所，因损得益之象", "counselZh": "君子以征忿窒欲", "trendZh": "现况诸事不顺，有破财之象，虽先损失，但后反而得益，因祸得福"},
  {"number": 42, "slug": "increase", "nameZh": "风雷益", "shortNameZh": "益", "imageZh": "强风配快雷，声威增长之象，长男配长女，夫妇合体，增益儿孙之象", "counselZh": "君子以见善则迁，有过则改", "trendZh": "现正当吉运，可得贵人之助而成功，宜施惠于人，施比受更有福"},
  {"number": 43, "slug": "breakthrough", "nameZh": "泽天夬", "shortNameZh": "夬", "imageZh": "泽水积满而泛滥成灾，滔天之势。又五阳爻之盛势必除去唯一阴爻，故一阴孤立", "counselZh": "君子以施禄及下，居德则忌", "trendZh": "目前虽吉，但困难及变动正在蕴酿中，宜提高警觉，忌骄傲，防口舌是非"},
  {"number": 44, "slug": "coming-to-meet", "nameZh": "天风姤", "shortNameZh": "姤", "imageZh": "风无孔不入，所吹到之处，暴露其间之物体，无一不与之相遇，为邂逅之意", "counselZh": "后以施命诰四方", "trendZh": "阴长阳消，注意桃色纠纷，诸事阻滞，宜慎重行事"},
  {"number": 45, "slug": "gathering-together", "nameZh": "泽地萃", "shortNameZh": "萃", "imageZh": "泽在地上，水聚于泥土中，滋养草木，生长茂盛", "counselZh": "君子以除戎器，戒不虞", "trendZh": "吉运昌盛，又得长辈提携，事业大利，但须防财务纠纷"},
  {"number": 46, "slug": "pushing-upward", "nameZh": "地风升", "shortNameZh": "升", "imageZh": "树木从地上不断向上，有进升之势", "counselZh": "君子以顺德，积小以高大", "trendZh": "名利双收，发展开运之象，宜向南方发展"},
  {"number": 47, "slug": "oppression", "nameZh": "泽水困", "shortNameZh": "困", "imageZh": "水在泽下，万物不生，喻君子困穷，小人滥盈之象", "counselZh": "君子以致命遂志", "trendZh": "诸事不如意，所谓龙游浅水遭虾戏"},
  {"number": 48, "slug": "the-well", "nameZh": "水风井", "shortNameZh": "井", "imageZh": "水被植物吸收，滋养树身又象征汲器入井取水，有节约重覆之意", "counselZh": "君子以劳民劝相", "trendZh": "井为静物，不能移动，故凡事不能进取主动，又缺乏冲劲，不如处之泰然更有利"},
  {"number": 49, "slug": "revolution", "nameZh": "泽火革", "shortNameZh": "革", "imageZh": "兑为金，被离火所烧，变革之象", "counselZh": "君子以治历明时", "trendZh": "凡事均在变动之中，宜去旧立新，以应革新之象"},
  {"number": 50, "slug": "the-cauldron", "nameZh": "火风鼎", "shortNameZh": "鼎", "imageZh": "木之上有离火，为燃炊烹饪之象，鼎有去旧立新，改过迁善之意", "counselZh": "君子以正位凝命", "trendZh": "时运仍佳，事业可成，但诸事不宜迟滞，及防有诉讼之累"},
  {"number": 51, "slug": "the-arousing", "nameZh": "震为雷", "shortNameZh": "震", "imageZh": "重雷发向，千里传声，有惊无险之象，亦有变动之意", "counselZh": "君子以恐惧修省", "trendZh": "表面昌盛风光，内里正处多事之秋，动荡不安之境"},
  {"number": 52, "slug": "keeping-still", "nameZh": "艮为山", "shortNameZh": "艮", "imageZh": "两重高山并峙，故宜止不宜进，阻塞之象", "counselZh": "君子以思不出其位", "trendZh": "凡事不宜妄动，前路受阻，只好待机而动"},
  {"number": 53, "slug": "development", "nameZh": "风山渐", "shortNameZh": "渐", "imageZh": "山上种有树木，逐渐生长，比喻循序渐进", "counselZh": "君子以居贤德善俗", "trendZh": "逐渐走向光明前途，凡事宜打根基，可得吉庆，但须防色情之难及文书错失"},
  {"number": 54, "slug": "the-marrying-maiden", "nameZh": "雷泽归妹", "shortNameZh": "归妹", "imageZh": "震长男在上，兑少女在下，女必归从，归即是出嫁，但少女配长男，非正常组合", "counselZh": "君子以永终知敝", "trendZh": "处事有违常理正道，先得其益，但随后祸事百端"},
  {"number": 55, "slug": "abundance", "nameZh": "雷火丰", "shortNameZh": "丰", "imageZh": "雷电交加，声势壮大，又离日动于天际，普照大地，皆为盛大之象", "counselZh": "君子以折狱致刑", "trendZh": "运势极强，为收获之时，但不宜贪得无厌，须知足常乐，要防是非、损财甚至火险"},
  {"number": 56, "slug": "the-wanderer", "nameZh": "火山旅", "shortNameZh": "旅", "imageZh": "火烧山野，火头遍布，所到之处，无一幸免，火头尤如行旅之人，无所定处", "counselZh": "君子以明慎用刑，而不留狱", "trendZh": "诸事变动不定，此时只好坚守信心，多参考他人意见，否则必有凶"},
  {"number": 57, "slug": "the-gentle", "nameZh": "巽为风", "shortNameZh": "巽", "imageZh": "此卦为两重巽风重叠，巽为入，风之所到无孔不入，尤如政令颁布，深入民心", "counselZh": "君子以申命行事", "trendZh": "波折重重，运势起落浮沉不定，要随机应变，心平气和，择善固执"},
  {"number": 58, "slug": "the-joyous", "nameZh": "兑为泽", "shortNameZh": "兑", "imageZh": "两泽相依，更得泽中映月，美景良辰，令人怡悦", "counselZh": "君子以朋友讲习", "trendZh": "悲喜交集，有誉有讥，守正道，诸事尚可称意"},
  {"number": 59, "slug": "dispersion", "nameZh": "风水涣", "shortNameZh": "涣", "imageZh": "风吹在水面上，流动四散，又有春风吹散严寒，令冰雪消解", "counselZh": "先王以享于帝，立庙", "trendZh": "虽有忧患，但终可解困，百事亨通，忌任性散慢"},
  {"number": 60, "slug": "limitation", "nameZh": "水泽节", "shortNameZh": "节", "imageZh": "泽为池沼，坎水在上，喻蓄积及约束水份不使流失，但水位过高，则成泛滥", "counselZh": "君子以制数度，议德行", "trendZh": "有志不能伸，诸事必须节制，不宜过份，更要戒酒色"},
  {"number": 61, "slug": "inner-truth", "nameZh": "风泽中孚", "shortNameZh": "中孚", "imageZh": "中孚为诚信意，风吹在泽水之上，泽水必相应而起波浪，为共鸣之象", "counselZh": "君子以议狱缓死", "trendZh": "凡事以「诚」待人，以「信」处事则诸事皆吉，心存邪念则凶"},
  {"number": 62, "slug": "small-exceeding", "nameZh": "雷山小过", "shortNameZh": "小过", "imageZh": "山上有雷，雷声虽大但被山阻隔，雷声减弱，即为「小过」", "counselZh": "君子以行过乎恭，丧过乎衰，用过乎俭", "trendZh": "诸事不利，宜行小事，不宜做大事，更防因小过失造成惊动，惹来是非争讼"},
  {"number": 63, "slug": "after-completion", "nameZh": "水火既济", "shortNameZh": "既济", "imageZh": "坎水在离火之上，水性下注，火势上炎，水火相济，完成之意", "counselZh": "君子以思患而预防之", "trendZh": "名利双收，成功之象，但须防物极必反，初吉后凶"},
  {"number": 64, "slug": "before-completion", "nameZh": "火水未济", "shortNameZh": "未济", "imageZh": "水性下注，火势向上，水火不交，阴阳不得正位，未能完成和未能成功之意", "counselZh": "君子以慎辨物居方", "trendZh": "运气欠佳，但必须耐心突破难关，终可成功，有初凶后吉之象"},
]

export const HEXAGRAM_ESSENCE_BY_SLUG: Record<string, HexagramEssence> =
  Object.fromEntries(HEXAGRAM_ESSENCE.map((item) => [item.slug, item]))
